server:
  port: 8080

spring:
  application:
    name: spring-demo
  # DB 配置
  datasource:
    dynamic:
      primary: db1-master
      p6spy: true
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        validation-query-timeout: 2
        filters: stat,wall,slf4j
      datasource:
        # db1-主库数据源s
        db1-master:
          url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
          username: root
          password: 123456
        # db1-从数据源
        db1-slave:
          url: jdbc:mysql://localhost:3306/user2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
          username: root
          password: 123456
        # db2-从数据源
        db2-slave:
          url: jdbc:mysql://localhost:3006/user3?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
          username: root
          password: 123456
  # Elasticsearch 配置
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  # HttpClient 配置
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      maxTotalConnect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      maxConnectPerRoute: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connectTimeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      readTimeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connectionRequestTimout: 200
      # 重试次数
      retryTimes: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keepAliveTime: 10
      # 针对不同的网址,长连接保持的存活时间,单位s,如果是频繁而持续的请求,可以设置小一点,不建议设置过大,避免大量无用连接占用内存资源
      keepAliveTargetHost:
        www.baidu.com: 5

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mybatis/mapper/db1/*.xml
    - classpath:mybatis/mapper/db2/*.xml
  typeAliasesPackage: com.yb.demo.pojo.model.db1;com.yb.demo.pojo.model.db2

# JetCache 配置
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: com.yb
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 200
        maxTotal: 1000
      uri:
        - redis://localhost:6380
        - redis://localhost:6381
        - redis://localhost:6382

# RocketMQ配置
rocketmq:
  name-server: localhost:9876
  producer:
    # RocketMQ的最佳实践中推荐：一个应用尽可能用一个Topic，消息子类型用tags来标识
    group: my-group

# Log 配置
logging:
  config: classpath:logback-spring.xml
  path: logs